options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'docker.io/pnpm/pnpm:node-20' # <-- FULLY QUALIFIED NAME
    id: 'Install dependencies'
    entrypoint: 'pnpm'
    args: ['install']

  - name: 'docker.io/pnpm/pnpm:node-20' # <-- FULLY QUALIFIED NAME
    id: 'Lint'
    entrypoint: 'pnpm'
    args: ['run', 'lint']
    waitFor: ['Install dependencies']

  - name: 'docker.io/pnpm/pnpm:node-20' # <-- FULLY QUALIFIED NAME
    id: 'Test'
    entrypoint: 'pnpm'
    args: ['run', 'test']
    waitFor: ['Install dependencies']
