steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: install
    entrypoint: 'pnpm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: lint
    entrypoint: 'pnpm' 
    args: ['run', 'lint']
    waitFor: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: test
    entrypoint: 'pnpm' 
    args: ['run', 'test']
    waitFor: ['install']


options: # Add this block at the top level of cloudbuild.pr.yaml
  logging: CLOUD_LOGGING_ONLY
