options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: gcr.io/cloud-builders/npm
  id: install
  args: ['install', '-g', 'pnpm@8', '&&', 'pnpm', 'install']

- name: gcr.io/cloud-builders/npm
  id: lint
  entrypoint: 'pnpm'
  args: ['run', 'lint']
  waitFor: ['install']

- name: gcr.io/cloud-builders/npm
  id: test
  entrypoint: 'pnpm'
  args: ['run', 'test']
  waitFor: ['install']

