# ────────────────────────────────────────────────────────────────
# Cloud Build pipeline for the “quote-api” Cloud Run service
#   • PR trigger  → _TARGET_ENV=staging  → build only
#   • Push-main   → _TARGET_ENV=prod     → build + deploy (+ optional canary)
# ────────────────────────────────────────────────────────────────
steps:
# 1) Build & push image
- id: build-image
  name: gcr.io/cloud-builders/docker
  args:
    - build
    - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/quote-api/quote-api:${SHORT_SHA}'
    - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/quote-api/quote-api:latest'
    - .

# 2) Push both tags
- id: push-image
  name: gcr.io/cloud-builders/docker
  args:
    - push
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/quote-api/quote-api:${SHORT_SHA}'
- id: push-latest
  name: gcr.io/cloud-builders/docker
  args:
    - push
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/quote-api/quote-api:latest'



# 3) Deploy to Cloud Run (ONLY for prod)
- id: deploy-prod
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      if [[ "$_TARGET_ENV" == "prod" ]]; then
        echo "🔄 Deploying to Cloud Run (prod)…"
        gcloud run deploy quote-api \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/quote-api/quote-api:latest \
          --revision-suffix=sha-${SHORT_SHA} \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated
      else
        echo "⚠️  Skipping deploy – _TARGET_ENV=$${_TARGET_ENV}"
      fi


# 3) Optional canary split (10 % to new rev) – ONLY for prod
- id: canary-split
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      if [[ "$_TARGET_ENV" == "prod" ]]; then
        echo "🔍 Fetching latest two revisions for canary split..."
        # Fetch the two most recent revisions
        # The first one is the new one (just deployed)
        # The second one is the previous stable one
        REVISIONS=$(gcloud run revisions list \
          --service=quote-api \
          --region=us-central1 \
          --platform=managed \
          --sort-by="~metadata.creationTimestamp" \
          --limit=2 \
          --format="value(metadata.name)")

        # Convert multi-line output to an array
        mapfile -t REV_ARRAY <<< "$REVISIONS"

        NEW_REVISION="${REV_ARRAY[0]}"
        PREVIOUS_STABLE_REVISION=""
        if [[ ${#REV_ARRAY[@]} -gt 1 ]]; then
          PREVIOUS_STABLE_REVISION="${REV_ARRAY[1]}"
        fi

        if [[ -z "$NEW_REVISION" ]]; then
          echo "❌ ERROR: Could not fetch new revision name. Skipping canary."
          exit 1 # Or handle error differently
        fi

        echo "🆕 New Revision: $NEW_REVISION"
        if [[ -n "$PREVIOUS_STABLE_REVISION" ]]; then
          echo "🕰️ Previous Stable Revision: $PREVIOUS_STABLE_REVISION"
          echo "🪄 Applying 10% canary to $NEW_REVISION, 90% to $PREVIOUS_STABLE_REVISION"
          gcloud run services update-traffic quote-api \
            --region=us-central1 \
            --platform=managed \
            --to-revisions="$${NEW_REVISION}=10,$${PREVIOUS_STABLE_REVISION}=90" \
            --project=$PROJECT_ID
        else
          echo "✅ Only one revision exists ($NEW_REVISION). All traffic (100%) automatically goes to it. No canary split needed."
          # If you want to explicitly tag the new revision as LATEST (though deploy should do it)
          # gcloud run services update-traffic quote-api \
          #   --region=us-central1 \
          #   --platform=managed \
          #   --to-revisions="$${NEW_REVISION}=100" \
          #   --project=$PROJECT_ID
        fi
      else
        echo "⚠️  Skipping canary – _TARGET_ENV=$${_TARGET_ENV}"
      fi

options:
  logging: CLOUD_LOGGING_ONLY

