steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/daring-emitter-457812-v7/quote-api', '.']

images:
  - 'gcr.io/daring-emitter-457812-v7/quote-api'

options:
  logging: CLOUD_LOGGING_ONLY 
