steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache','-t', 'gcr.io/daring-emitter-457812-v7/quote-api', '.']

 
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      - run
      - deploy
      - quote-api
      - --image=gcr.io/daring-emitter-457812-v7/quote-api
      - --platform=managed
      - --region=us-central1
      - --allow-unauthenticated


images:
  - 'gcr.io/daring-emitter-457812-v7/quote-api'

options:
  logging: CLOUD_LOGGING_ONLY 
