# ────────────────────────────────────────────────────────────────
# Cloud Build pipeline for the “quote-api” Cloud Run service
#   • PR trigger  → _TARGET_ENV=staging  → build only
#   • Push-main   → _TARGET_ENV=prod     → build + deploy (+ optional canary)
# ────────────────────────────────────────────────────────────────
steps:
# 1) Build & push image
- id: build-image
  name: us-central1-docker.pkg.dev/cloud-builders/docker
  args:
    - build
    - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/quote-api:${SHORT_SHA}'
    - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/quote-api:latest'
    - .

# 2) Deploy to Cloud Run (ONLY for prod)
- id: deploy-prod
  name: us-central1-docker.pkg.dev/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      if [[ "$_TARGET_ENV" == "prod" ]]; then
        echo "🔄 Deploying to Cloud Run (prod)…"
        gcloud run deploy quote-api \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/quote-api:latest \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated
      else
        echo "⚠️  Skipping deploy – _TARGET_ENV=$${_TARGET_ENV}"
      fi

# 3) Optional canary split (10 % to new rev) – ONLY for prod
- id: canary-split
  name: us-central1-docker.pkg.dev/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      if [[ "$_TARGET_ENV" == "prod" ]]; then
        echo "🪄 Updating traffic split (10 % canary)…"
        gcloud run services update-traffic quote-api \
          --to-revisions=${SHORT_SHA}=10,latest=90 \
          --region=us-central1 \
          --platform=managed
      else
        echo "⚠️  Skipping canary – _TARGET_ENV=$${_TARGET_ENV}"
      fi

options:
  logging: CLOUD_LOGGING_ONLY

