steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install'
    entrypoint: 'pnpm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Lint'
    entrypoint: 'pnpm' 
    args: ['run', 'Lint']
    waitFor: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Test'
    entrypoint: 'pnpm' 
    args: ['run', 'Test']
    waitFor: ['Install']


