# cloudbuild.pr.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'node:20' # Use the official Node image which includes npx
    id: 'Install dependencies'
    entrypoint: 'npx' # Use npx to run pnpm
    args: ['pnpm', 'install']
    # dir: '/workspace' # Cloud Build usually mounts /workspace, this is default

  - name: 'node:20' # Use the same Node image
    id: 'Lint'
    entrypoint: 'npx'
    args: ['pnpm', 'run', 'lint']
    waitFor: ['Install dependencies'] # Corrected from your previous example
    # dir: '/workspace'

  - name: 'node:20' # Use the same Node image
    id: 'Test'
    entrypoint: 'npx'
    args: ['pnpm', 'run', 'test']
    waitFor: ['Install dependencies'] # Corrected from your previous example
    # dir: '/workspace'
