steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Hello from PR-trigger sanity test"
        gcloud info

options:
  logging: CLOUD_LOGGING_ONLY

