# ────────────────────────────────────────────────────────────────
# Cloud Build pipeline for the “quote-api” Cloud Run service
#   • PR trigger  → _TARGET_ENV=staging  → build only
#   • Push-main   → _TARGET_ENV=prod     → build + deploy (+ optional canary)
# ────────────────────────────────────────────────────────────────
steps:
# 1) Build & push image
- id: build-image
  name: gcr.io/cloud-builders/docker
  args:
    - build
    - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/quote-api/quote-api:${SHORT_SHA}'
    - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/quote-api/quote-api:latest'
    - .

# 2) Push both tags
- id: push-image
  name: gcr.io/cloud-builders/docker
  args:
    - push
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/quote-api/quote-api:${SHORT_SHA}'
- id: push-latest
  name: gcr.io/cloud-builders/docker
  args:
    - push
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/quote-api/quote-api:latest'



# 3) Deploy to Cloud Run (ONLY for prod)
- id: deploy-prod
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      if [[ "$_TARGET_ENV" == "prod" ]]; then
        echo "🔄 Deploying to Cloud Run (prod)…"
        gcloud run deploy quote-api \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/quote-api/quote-api:latest \
          --revision-suffix=sha-${SHORT_SHA} \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated
      else
        echo "⚠️  Skipping deploy – _TARGET_ENV=$${_TARGET_ENV}"
      fi

# 3) Optional canary split (10 % to new rev) – ONLY for prod
- id: canary-split
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      if [[ "$_TARGET_ENV" == "prod" ]]; then
        # Fetch the latest revision name (always valid format)
        REVISION=$(gcloud run revisions list \
          --service=quote-api \
          --region=us-central1 \
          --platform=managed \
          --sort-by=~metadata.creationTimestamp \
          --limit=1 \
          --format='value(metadata.name)')

        echo "🪄 Applying canary split to revision $REVISION"
        gcloud run services update-traffic quote-api \
          --region=us-central1 \
          --platform=managed \
          --to-revisions=$${REVISION}=10,latest=90
      else
        echo "⚠️  Skipping canary – _TARGET_ENV=${_TARGET_ENV}"
      fi

options:
  logging: CLOUD_LOGGING_ONLY

