# This file solves the logging error.
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # STEP 0: Install dependencies
  - name: 'node:20'
    id: 'Install Dependencies'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      npm install -g pnpm
      pnpm install

  # STEP 1: Run Linter
  - name: 'node:20'
    id: 'Lint'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      npm install -g pnpm
      pnpm run lint
    waitFor: ['Install Dependencies']

  # STEP 2: Run Tests
  - name: 'node:20'
    id: 'Test'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      npm install -g pnpm
      pnpm run test
    waitFor: ['Install Dependencies']
