# charts/quote-api/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quote-api-ksa
  labels:
    {{- include "quote-api.labels" . | nindent 4 }}
  annotations:
     iam.gke.io/gcp-service-account: quote-api-gsa@{{ .Values.projectId }}.iam.gserviceaccount.com
